apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "polyaxon.fullname" . }}-config
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.api }}
data:
  debug: {{ .Values.debug | quote }}
  cluster-id: ""
  node-selectors-experiments: {{ toJson .Values.nodeSelectors.experiments | quote }}
  amqp-url: {{ template "rabbitmq.fullname" . }}:5672
  redis-result-backend-url: redis://{{ template "redis.fullname" . }}:6379/0
  redis-job-containers-url: redis://{{ template "redis.fullname" . }}:6379/3
  redis-to-stream-url: redis://{{ template "redis.fullname" . }}:6379/4
  container-name-job: "polyaxon-experiment-job"
  container-name-sidecar: "polyaxon-experiment-job-sidecar"
  container-name-plugin-job: "polyaxon-plugin-job"
  sidecar-persist: "0"
  sidecar-log-sleep-interval: "1"
